<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="laptopcuatruong" failures="1" tests="9" name="TESTCASES.Test_Add_Article" time="152.414" errors="0" timestamp="2023-12-11T13:02:53 ICT" skipped="0">
  <testcase classname="TESTCASES.Test_Add_Article" name="test_Add_Article" time="12.713"/>
  <system-out/>
  <testcase classname="TESTCASES.Test_Add_Article" name="test_Add_Article" time="12.607"/>
  <system-out/>
  <testcase classname="TESTCASES.Test_Add_Article" name="test_Add_Article" time="12.705"/>
  <system-out/>
  <testcase classname="TESTCASES.Test_Add_Article" name="test_Add_Article" time="12.676"/>
  <system-out/>
  <testcase classname="TESTCASES.Test_Add_Article" name="test_Add_Article" time="12.577">
    <failure message="Testcase thất bại expected [Bài viết chưa được đăng. Vui lòng thêm tiêu đề bài viết.] but found [Bài viết đã được đăng. Xem bài viết]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Testcase thất bại expected [Bài viết chưa được đăng. Vui lòng thêm tiêu đề bài viết.] but found [Bài viết đã được đăng. Xem bài viết]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at PAGES.add_article_page.check_Add_article(add_article_page.java:149)
at PAGES.add_article_page.Add_article(add_article_page.java:29)
at TESTCASES.Test_Add_Article.test_Add_Article(Test_Add_Article.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_Add_Article -->
  <system-out/>
  <testcase classname="TESTCASES.Test_Add_Article" name="test_Add_Article" time="15.282"/>
  <system-out/>
  <testcase classname="TESTCASES.Test_Add_Article" name="test_Add_Article" time="12.464"/>
  <system-out/>
  <testcase classname="TESTCASES.Test_Add_Article" name="test_Add_Article" time="48.863"/>
  <system-out/>
  <testcase classname="TESTCASES.Test_Add_Article" name="test_Add_Article" time="12.527"/>
  <system-out/>
</testsuite> <!-- TESTCASES.Test_Add_Article -->
